export default {
  index: 'Feature Overview',
  sidebar: 'Sidebar Panel',
  spaces: 'Spaces',
  pinnedItems: 'Pinned Items',
  recentItems: 'Recent Items',
  smartFolders: 'Smart Folders',
  tags: 'Tags & AI Tagging',
  globalShortcuts: 'Global Shortcuts',
  smartShortcuts: 'Smart Shortcuts',
  commandPanel: 'Command Panel',
  floatingButton: 'Floating Button',
  mouseTriggers: 'Mouse Triggers',
  dockmode: 'Dockmode',
  browserSelection: 'Browser Selection',
  browserImport: 'Browser Import',
  liveTabs: 'Live Tabs',
  finderIntegration: 'Finder Integration',
  sync: 'iCloud Sync'
}
